### ISSUE TITLE
Support adding barrier to `perceval.Circuit`

### ISSUE THREAD

**Issue by king-p3nguin** [Quandela/Perceval#275]
In qiskit, [barrier](https://qiskit.org/documentation/stubs/qiskit.circuit.library.Barrier.html) will separate the circuit into two distinct areas for visual purposes. (Also, it will prevent combining gates through barriers while using transpiler) To break components into separate groups, I use

```python
circ.add(0, comp.PERM(list(range(circ.m))))
```

so that it works like a barrier, but it would be nice if I can add barriers to circuit not as a component.

**Comment by ericbrts** [comment]
Hello,

We plan to introduce such a "barrier" separator in the next version of Perceval. Thank you very much for your input.

Best wishes,
Eric

**Comment by burlemarxiste** [comment]
I don't know if this has been implemented, but since I had to mess with the rendering code for the herald bug fix, I quickly did it (through an `IDENTITY` unitary with custom rendering code, and a new method for Circuit, `c.barrier()`).

Are there any implementation details, side effects or naming preferences to be aware of or can I send a PR for this?

![barrier_test0](https://github.com/Quandela/Perceval/assets/171129116/24b16820-993d-4b36-96cc-4b47d06b2c02)
![barrier_test2](https://github.com/Quandela/Perceval/assets/171129116/63f10248-6977-4a75-b07a-32dab33d5041)

**Comment by ericbrts** [comment]
Hi @burlemarxiste ,

No Barriers were not implemented yet in Perceval. The most recent "stable" version is located in the branch "release/0.11.0"

**Comment by burlemarxiste** [comment]
Would you be interested in a PR for this feature? I did it as part of my fix of the herald rendering bug (unitaryhack task).
